# Generated by Django 2.1.1 on 2018-12-19 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('jobname', models.CharField(max_length=160)),
                ('jobtype', models.CharField(default=1, max_length=160)),
                ('priority', models.IntegerField(default=5)),
                ('disabled', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job',
                'ordering': ['-created_date'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobs',
            unique_together={('jobname', 'jobtype')},
        ),
    ]
